server:
  port: 8088
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    # 这个设置只对Date Timestamp类型有效
    date-format: yyyy-MM-dd HH:mm:ss
## mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
#  type-aliases-package: com.lantin.web.domain
#  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
#  type-aliases-super-type: com.lantin.common.domain.base.BasePo
#  configuration:
#    use-generated-keys: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-prefix: mp-sql-log
#  global-config:
#    db-config:
#      id-type: auto
## 项目个人配置
#com:
#  lantin:
#    id-worker:
#      data-center-id: 3
#      work-id: 3
test:
  properties:
    age: 18
    name: zhangsan
    str: win

